# This is a basic workflow to help you get started with Actions

name: CI

on:
  issue_comment:
    types: [created]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.html_url, '/pull/') && startsWith(github.event.comment.body, '/submit')
    steps:
      - name: Get branch name
        id: upstreambranch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::set-output name=branchname::$(curl -H "Authorization: token ${GITHUB_TOKEN}" ${{ github.event.issue.pull_request.url }} | jq '.head.ref' | sed 's/\"//g')"
        
      - name: Display branch name
        run: |
          echo ${{ steps.upstreambranch.outputs.branchname }}
          
      - name: Create bitrise API call
        if: startsWith(steps.upstreambranch.outputs.branchname, 'release')
        env:
          BITRISE_SLUG: ${{ secrets.BITRISE_SLUG }}
          BITRISE_TOKEN: ${{ secrets.BITRISE_TOKEN }}
        run: |
          echo "https://api.bitrise.io/v0.1/apps/${BITRISE_SLUG}/builds"
          echo $(curl -X GET -H "Authorization: token ${GITHUB_TOKEN}" https://api.bitrise.io/v0.1/apps/${BITRISE_SLUG}/builds)
        
