# This is a basic workflow to help you get started with Actions

name: CI

on:
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.html_url, '/pull/') && startsWith(github.event.comment.body, '/submit')
    steps:
      - name: Get branch name
        id: upstream_branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RESPONSE=$(curl -H "Authorization: token ${GITHUB_TOKEN}" ${{ github.event.issue.pull_request.url }})
          echo ${RESPONSE}
          echo "::set-output name=branchname::$(echo ${RESPONSE} | jq '.head.ref' | sed 's/\"//g')"
          echo "::set-output name=pull_request_title::$(echo $RESPONSE | jq '.title')"
          
      - name: Output
        run: |
          echo ${{ steps.upstream_branch.outputs.branchname }}
          echo ${{ steps.upstream_branch.outputs.pull_request_title }}
