# This is a basic workflow to help you get started with Actions

name: CI

on:
  issue_comment:
    types: [created]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.html_url, '/pull/') && startsWith(github.event.comment.body, '/submit')
    steps:
      - name: Get branch name
        id: branch_name
        run: |
          echo ${{ github.event.issue.pull_request.url }}
