name: echo

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get_swift_version
        id: get_swift_version
        run: |
          swift --version
          swift_version=`swift --version`
          echo "::set-output name=swift_version::$swift_version"
          
      - name: Cache Build Tools
        uses: actions/cache@v2
        env:
          cache-name: swiftformat-triggerd-by-main-merge
        with:
          path: ./README.md
          key: v1-${{ runner.os }}-${{ env.cache-name }}-${{ steps.get_swift_version.outputs.swift_version }}

      #- name: debug
      #  run: |
      #    echo ${{ steps.get_swift_version.outputs.swift_version }}
