name: echo

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get_swift_version
        run: |
          swift --version
          swift_version=$(swift --version)
          echo "::set-output name=swift_version::$(swift --version)"

      - name: debug
        run: |
          echo ${{ steps.get_swift_version.outputs.swift_version }}
