name: Update Package.resolved for Renovate

on:
  pull_request:
    types: 
      - opened
    paths: 
      - test.txt

jobs:
  test:
    if: startsWith(github.head_ref, 'test/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Check
        run: |
          git rev-parse HEAD
          echo ${{ github.event.pull_request.head.sha }}
      - name: Add diff
        run: |
          echo hoge >> hoge.txt
      - name: Commit
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "New commit"
          git push
