name: Release

on:
  workflow_dispatch:
    inputs:
      job:
        description: 'Job'
        required: true
        default: 'release_draft'
        type: choice
        options:
          - 'release_draft'
          - 'update_google_play_store'
      build_flavor:
        description: 'Build Flavor'
        required: true
        default: 'production'
        type: choice
        options:
          - development
          - staging
          - production
      priority:
        description: 'In app update priority'
        required: false
        type: choice
        options:
          - '0'
          - '1'
          - '2'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CIRCLE_TOKEN: ${{ secrets.CIRCLE_TOKEN }}
    steps:
      - name: Get tag
        id: get_tag
        run: |
          : # https://github.com/orgs/community/discussions/26686
          echo ${GITHUB_REF}
          echo ${{github.ref_name}}
          if [[ ${GITHUB_REF#refs/tags/} == *"refs/heads/"* ]]; then
            echo "Please select tag"
            exit 1
          fi
          echo "tag=${{github.ref_name}}" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.get_tag.outputs.tag }}
      - name: Execute script
        run: |
          ./bin/script.sh -j ${{ inputs.job }} -r ${{ steps.get_tag.outputs.tag }} -f ${{ inputs.build_flavor }} -p ${{ inputs.priority }}
