name: Release

on:
  workflow_dispatch:
    inputs:
      job:
        description: 'Job'
        required: true
        default: 'release_draft'
        type: choice
        options:
          - 'release_draft'
          - 'update_google_play_store'
      build_flavor:
        description: 'Build Flavor'
        required: true
        type: choice
        options:
          - development
          - staging
          - production
      priority:
        description: 'In app update priority'
        required: false
        type: choice
        options:
          - '0'
          - '1'
          - '2'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CIRCLE_TOKEN: ${{ secrets.CIRCLE_TOKEN }}
      SLACK_ICON: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
    steps:
      - name: Get tag
        id: get_tag
        run: |
          : # https://github.com/orgs/community/discussions/26686
          echo ${GITHUB_REF}
          echo ${{github.ref_name}}
          if [[ ${{ github.ref }} == *"refs/heads/"* ]] && [[ ${{ inputs.build_flavor }} = 'production' ]]; then
            echo "Please select tag"
            exit 1
          fi
          echo "tag=${{github.ref_name}}" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.get_tag.outputs.tag }}
      - name: Execute script
        id: script
        run: |
          result=$(./bin/script.sh -j ${{ inputs.job }} -r ${{ steps.get_tag.outputs.tag }} -f ${{ inputs.build_flavor }} -p ${{ inputs.priority }} | grep build_url)
          build_url=$(echo $result | cut -d '"' -f4) # ` "build_url" : "https://circleci.com/gh/mitene/Android/123710",` という出力になることが前提
          echo "build_url=${build_url}" >> $GITHUB_OUTPUT
      - name: echo
        run: |
          echo "${{ steps.script.outputs.build_url }}"
      - name: Send GitHub Action trigger message
        if: success()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: ${{ env.SLACK_ICON }}
          SLACK_MESSAGE: "job: ${{ inputs.job }}\nbuild_flavor: ${{ inputs.build_flavor }}\npriority: ${{ inputs.priority }}\nbuild_url: ${{ steps.script.outputs.build_url }}"
          SLACK_TITLE: "Result"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          MSG_MINIMAL: ref,actions url
          SLACK_FOOTER: ""
        # uses: slackapi/slack-github-action@v1.24.0
        # with:
        #   payload: |
        #     {
        #       "text": "${{ inputs.job }} が開始しました",
        #       "attachments": [
        #         {
        #           "title": "${{ github.workflow }} #${{ github.run_number }}",
        #           "title_link": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
        #           "color": "#36a64f",
        #           "fields": [
        #             {
        #               "title": "job",
        #               "value": "${{ inputs.job }}",
        #               "short": "true"
        #             },
        #             {
        #               "title": "build_flavor",
        #               "value": "${{ inputs.build_flavor }}",
        #               "short": "true"
        #             },
        #             {
        #               "title": "revision",
        #               "value": "${{ steps.get_tag.outputs.tag }}",
        #               "short": "true"
        #             },
        #             {
        #               "title": "priority",
        #               "value": "${{ inputs.priority }}",
        #               "short": "true"
        #             },
        #             {
        #               "title": "build_url",
        #               "value": "${{ steps.script.outputs.build_url }}"
        #             }
        #           ]
        #         }
        #       ]
        #     }
        # env:
        #   SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        #   SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
