name: Release

on:
  workflow_dispatch:
    inputs:
      job:
        description: 'Job'
        required: true
        default: 'release_draft'
        type: choice
        options:
          - 'release_draft'
          - 'update_google_play_store'
      build_flavor:
        description: 'Build Flavor'
        required: true
        default: 'production'
        type: choice
        options:
          - development
          - staging
          - production
      priority:
        description: 'In app update priority'
        required: false
        type: choice
        options:
          - '0'
          - '1'
          - '2'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CIRCLE_TOKEN: ${{ secrets.CIRCLE_TOKEN }}
    steps:
      - name: Get tag
        id: get_tag
        run: |
          : # https://github.com/orgs/community/discussions/26686
          echo ${GITHUB_REF}
          echo ${{github.ref_name}}
          : #if [[ ${{ github.ref }} == *"refs/heads/"* ]]; then
          : #  echo "Please select tag"
          : #  exit 1
          : #fi
          echo "tag=${{github.ref_name}}" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.get_tag.outputs.tag }}
      - name: Execute script
        id: script
        run: |
          result=$(./bin/script.sh -j ${{ inputs.job }} -r ${{ steps.get_tag.outputs.tag }} -f ${{ inputs.build_flavor }} -p ${{ inputs.priority }})
          response=$(echo $result | grep TITLE)
          echo $response
          echo "response=${response}" >> $GITHUB_OUTPUT
      - name: echo
        run: |
          echo "${{ steps.script.outputs.response }}"
      - name: Send GitHub Action trigger message
        if: success()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: |
            {
              "text": "${{ inputs.job }} が開始しました",
              "attachments": [
                {
                  "title": "${{ github.workflow }} #${{ github.run_number }}",
                  "title_link": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                  "color": "#36a64f",
                  "fields": [
                    {
                      "title": "job",
                      "value": "${{ inputs.job }}"
                    },
                    {
                      "title": "build_flavor",
                      "value": "${{ inputs.build_flavor }}"
                    },
                    {
                      "title": "revision",
                      "value": "${{ steps.get_tag.outputs.tag }}"
                    },
                    {
                      "title": "priority",
                      "value": "${{ inputs.priority }}"
                    },
                    {
                      "title": "build_url",
                      "value": "${{ steps.request_release.outputs.result }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
