name: SwiftFormat daily

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Status
        run: |
          echo "failure"
          exit 1
      - name: something step
        run: |
          echo "something"
      - name: create json
        if: always()
        run: >
          jq -n
          --arg text `echo hoge`
          --argjson data "$( \
            jq -n \
            --arg title "${{ github.workflow }} #${{ github.run_number }}" \
            --arg title_link "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
            --arg text "branch: ${{ github.event.pull_request.head.ref }}" \
            '{ title: $title, title_link: $title_link, color: "#ff0000", text: $text }' \
          )"
          '{ text: $text , attachments: $data}'
      - name: Send GitHub Action trigger message
        if: failure()
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "SwiftFormat daily が失敗しました`echo hogehoge`"
            attachments: 
              - title: "${{ github.workflow }} #${{ github.run_number }}"
                title_link: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                color: "#ff0000"
                fields:
                  - title: "Branch"
                    value: ${{ github.event.pull_request.head.ref }}
