name: SwiftFormat daily

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Status
        run: |
          echo "failure"
          exit 1
      - name: something step
        run: |
          echo "something"
      - name: create json
        if: always()
        run: >
          jq -n
          "{ \
            text: \"`echo hoge`\", \
            attachments: [ \
              { \
                title: \"${{ github.workflow }} \#${{ github.run_number }}\", \
                title_link: \"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\", \
                color: \"\#ff0000\", \
                fields: [ \
                  title: \"Branch\", \
                  value: \"${{ github.event.pull_request.head.ref }}\" \
                ] \
              } \
            ] \
          }"
          > payload.json
      - name: check
        if: always()
        run: |
          cat payload.json
      - name: Send GitHub Action trigger message
        if: failure()
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload-file-path: "./payload.json"
