name: SwiftFormat

on:
  workflow_dispatch:

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    env:
      MINT_PATH: ${{ vars.MINT_PATH }}
    steps:
      - uses: actions/checkout@v4
      - uses: irgaly/setup-mint@v1
        with:
          bootstrap: false
          
      - name: Add $HOME/bin to path
        run: echo "$HOME/bin" >> $GITHUB_PATH

      - name: Format
        run: |
          echo "$HOME/bin"
          echo $GITHUB_PATH
          mint help
